---

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - .:/app
    environment:
      UVICORN_LOG_LEVEL: debug
      UVICORN_RELOAD: 1
