---
services:

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
      target: fastapi
    ports:
      - 8000:80
    working_dir: /mnt/app
    volumes:
      - .:/mnt/app

  assets:
    image: node:18
    working_dir: /mnt/app/assets
    volumes:
      - .:/mnt/app
    command: sh -c "yarn && exec yarn run dev"
